feat: intro-to-anchor-draft
Unboxed-Software/solana-course pull request #112
Opened 2022-08-08 19:25 UTC by ZYJLiu

2022-08-12 15:57 UTC, ixmorrow commented on content/intro-to-anchor.md
> +- **Anchor** allows you more easily build secure programs by performing certain security checks, requiring account validation, and providing a simply way to implement additional checks.
From -> **Anchor** allows you more easily
To: **Anchor** allows you to more easily

2022-08-12 15:58 UTC, ixmorrow commented on content/intro-to-anchor.md
> +- **Anchor** allows you more easily build secure programs by performing certain security checks, requiring account validation, and providing a simply way to implement additional checks.
Typo:
From -> and providing a simply way to implement additional checks.
To -> and providing a simple way to implement additional checks.

2022-08-12 16:02 UTC, ixmorrow commented on content/intro-to-anchor.md
> +Anchor is a framework building Solana programs. The Anchor framework organizes a program in distinct sections that separates the instruction logic from account validation and security check. This sep
Anchor is a framework for building Solana programs. The Anchor framework organizes a program into distinct sections that separates the instruction logic from account validation and security checks.

2022-08-12 16:07 UTC, ixmorrow commented on content/intro-to-anchor.md
> +Anchor also enables you to quickly build Solana programs by abstracting away various tasks such as serialization and deserialization of account. This is accomplished by bundling various boilerplate c
Anchor also enables you to quickly build Solana programs by abstracting away various tasks such as the serialization and deserialization of an account.  This is accomplished by bundling boilerplate code into macros, allowing you to focus on the business logic of your program. Additionally, Anchor is designed to inherently handle many common security checks while allowing you to easily define additional checks to help you build more secure programs.

The organization and abstraction capabilities of Anchor, make Solana programs much easier to read and write.

2022-08-16 04:52 UTC, ZYJLiu commented on content/intro-to-anchor.md
> +We're going to build a simple Anchor program using Solana Playground. The Solana Playground is a tool that allows you to write and deploy Solana programs from the browser.
Yea for sure. Using SolPg just for this first intro lesson.
Local setup next lesson. 
Following local setup lesson will be rebuilding movie review program in Anchor locally.

2022-08-16 05:00 UTC, ZYJLiu commented on content/intro-to-anchor.md
> +Try to do this independently if you can! But if you get stuck, feel free to reference the [solution code](https://beta.solpg.io/62f14c6df6273245aca4f636).
Previous solution code is for demo.
Last line solution code is for challenge. 

The initialize instruction is slightly different between the two.
Initialize instruction in challenges requires an `input` parameter as instruction data

2022-10-14 23:01 UTC, jamesrp13 requested changes
@ZYJLiu have a look at my comments, but also look at my commit on your branch and tell me what you think. If you're good with it lmk and I'll approve and merge

2022-10-17 20:23 UTC, merged