docs: Add YAML front matter to the course
Unboxed-Software/solana-course pull request #205
Opened 2023-03-30 10:37 UTC by cdhiraj40

### Description
This pull request adds YAML front matter to the course Markdown files. The front matter includes a title and other metadata such as objectives, making it easier to create a detailed table of contents or index for the course.

cc @jamesrp13

2023-03-30 14:07 UTC, cdhiraj40 commented
I will be updating PR with headlines synced with the course in the SolDev repo: https://github.com/ironforge-cloud/soldev-ui/tree/master/content/course

Current Tl;Dr; headings are too big!

2023-04-04 18:25 UTC, jamesrp13 requested changes

2023-04-04 18:25 UTC, jamesrp13 commented on content/type-cosplay.md
> +- Use Anchor's `Acc
Typo here

2023-04-04 18:25 UTC, jamesrp13 commented on course-module.json
> +    {
Can we rename this to `course-structure.json`

2023-04-04 18:31 UTC, jamesrp13 approved these changes

2023-04-04 18:32 UTC, merged