Fixes to existing content
Unboxed-Software/solana-course pull request #216
Opened 2023-08-30 11:56 UTC by mikemaccana

fix: grammar: apostrophe of possession is commonly dropped with inanimate items
fix: use descriptive text for links instead of 'here'
fix: PDAs are objectively *not* public keys. 
fix: solana uses 'secret key' rather than 'private key' per web3.js and https://github.com/solana-foundation/developer-content/blob/main/docs/terminology.md
fix: use wallet standard - there is no need to install adapters for specific wallets anymore, Jordan Sexton can give details
fix: avoid overuse of the word 'effectively'

2023-09-01 16:40 UTC, jamesrp13 commented on content/bump-seed-canonicalization.md
> +In this scenario, Anchor *does* allow you to specify the bump to use to derive the PDA with `bump = <some_bump>`. The intent here is not for you to use arbitrary bumps, but rather to let you optimize
We appear to have difference of opinion about using the possessive for accounts. IMO this and the next couple changes should remain "account's" with an apostrophe to indicate belonging to the account. Would you mind letting me know why you feel the opposite?

2023-09-01 16:46 UTC, jamesrp13 requested changes
These are all great improvements, thank you. My only hesitation is the shift from "account's" as a clear possessive to "accounts" denoting plurality. Let's hash that one out before we merge

2023-09-04 11:04 UTC, mikemaccana commented
> These are all great improvements, thank you. My only hesitation is the shift from "account's" as a clear possessive to "accounts" denoting plurality. Let's hash that one out before we merge

Updated! Feel free to merge when you get a moment.

2023-09-04 16:10 UTC, jamesrp13 approved these changes

2023-09-04 16:10 UTC, merged