feat: add hello world to module 3
Unboxed-Software/solana-course pull request #61
Opened 2022-06-10 22:55 UTC by jamesrp13

2022-06-14 18:23 UTC, mixelpixel approved these changes
Hello, world! looks good

2022-06-16 02:21 UTC, jamesrp13 commented
> @jamesrp13 noting here per the Movie Review/Basic Program Pt 1 PR [#64 (comment)](https://github.com/Unboxed-Software/solana-course/pull/64#discussion_r896248656), I think we might want to add an "iterator" section to the Hello World Program lesson?
> 
> ```
>     // Iterators
>     let v1 = vec![1, 2, 3];
>     /* create the iterator over the vector: */
>     let mut v1_iter = v1.iter();
>     /* use the iterator to get the first item */
>     let first_item = v1_iter.next();
> ```

Not sure what I wrote in the comment, but what I meant was to add iterator section to the movie review pt 2 lesson, not the hello world lesson

2022-06-20 17:50 UTC, ZYJLiu approved these changes

2022-06-20 18:22 UTC, mixelpixel requested changes
1. optional: remove weird dots
2. fix: `use` keyword

2022-06-20 18:22 UTC, mixelpixel commented on content/hello-world-program.md
> +
weird, my text editor shows two weird little orange dots here... not sure what they are but jsyk see pic:
![pr61-weirdOrangeDots](https://user-images.githubusercontent.com/18152993/174658455-1e2f810d-f2bf-4596-be68-65cec5221f97.png)

2022-06-20 18:22 UTC, mixelpixel commented on content/hello-world-program.md
> +However, with the [`use`](https://doc.rust-lang.org/stable/book/ch07-04-bringing-paths-into-scope-with-the-use-keyword.html) we can bring an item into scope so that it can be reused throughout a file
fix: awk 
add "keyword" --> with the `use` keyword we can bring

2022-06-20 21:32 UTC, merged